import { test } from 'node:test'
import assert from 'node:assert/strict'
import { extractSnapshot, snapshotTables } from './snapshot-format.mjs'

test('accepts quote-all-identifiers dumps generated by the Supabase CLI', () => {
  const dump = snapshotTables.map((table) => `COPY "${table.replace('.', '"."')}" ("id") FROM stdin;\n\\.\n`).join('\n')
  const result = extractSnapshot(dump)
  assert.equal(Object.keys(result.counts).length, snapshotTables.length)
  assert.equal(result.counts['auth.users'], 0)
})
